config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :currencies

  get 'dashboard/capture'
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
    has_many :transactions, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :currency
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    

end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:endpoint, :name)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include TransactionsHelper
  
  def index
    @currencies = Currency.all;
    return @currencies
  end

  def capture
    Currency.all.each do |c|
      capture_and_save(c)
    end 
    flash[:notice] = "Updated"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
    def capture_and_save(currency)
        fetch_data = CaptureService.call(currency.endpoint)

        if fetch_data['error_type'].present? || fetch_data == false
            return false
        end

        last_trans = get_last_transacton_by_id(currency.id)

        unless duplicate_transaction?(fetch_data, last_trans)
            currency.transactions.create(last: fetch_data['last'], bid: fetch_data['bid'], ask: fetch_data['ask'], trans_time: fetch_data['transition_time'])
        end
    end

    def duplicate_transaction?(fetched, latest)
        return  latest&.bid== fetched['bid'].to_f && latest&.ask == fetched['ask'].to_f && latest&.last == fetched['last'].to_f
    end

    def get_last_transacton_by_id(id)
        Transaction.where(currency_id: id).last
    end
    
end

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
        <% currency.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :endpoint %>
    <%= form.text_field :endpoint %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.haml
%p#notice
  = notice

%h1 Currencies

%table
  %thead
    %tr
      %th Name
      %th Endpoint
      %th{colspan:3}
  %tbody
    - @currencies.each do |currency|
      %tr
        %td 
          = currency.name
        %td 
          = currency.endpoint
        %td 
          = link_to 'Show', currency
        %td
          = link_to 'Edit', edit_currency_path(currency)
        %td 
          = link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'Home', root_path

= link_to 'New Currency', new_currency_path

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.haml
%p#notice
  = notice

%p
  %strong Name:
  = @currency.name
%p
  %strong Endpoint:
  = @currency.endpoint

%ul
  - @currency.transactions.order(created_at: :desc).each do |t|
    %li
      bid:
      =t.bid

      last:
      =t.last

      ask:
      =t.ask

      trans_time:
      =t.trans_time

= link_to 'Edit', edit_currency_path(@currency)  |
= link_to 'Back', currencies_path 

app/views/dashboard/index.html.haml
%p#notice
   = notice
%h1 Dashboard#index

%p Find me in app/views/dashboard/index.html.erb

%p
   now you have
   = @currencies&.count
   currencies

%table
   %thead
      %tr
         %th Name
         %th Records
         %th Latest Ask
         %th Latest Bid
         %th Latest last
         %th 
   %tbody
      - @currencies.each do |c|
         %tr
            %td 
               =c.name
            %td
               =c.transactions&.count
            %td
               =c.transactions&.last&.ask
            %td
               =c.transactions&.last&.bid
            %td
               =c.transactions&.last&.last
            %td
               = link_to 'Show History', c

%ul
   - @currencies.each do |c|
      %li 
         =c.name

         and has
         =c.transactions&.count
         records

         latest price:
         =c.transactions&.last&.ask

         view detail 
         = link_to 'Show History', c


= link_to 'Capture', dashboard_capture_path

= link_to 'New Currency', new_currency_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coinjar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>